name: Deployment workflow
on: push
jobs:
    
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Git code
              uses: actions/checkout@v3
            - name: Install Dependens
              run: npm ci
            - name: run lint
              run:   npm run lint
            - name: Testing
              run: npm test    
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Git code
              uses: actions/checkout@v3
            - name: Install Dependens
              run: npm ci
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo Deploying...
                